### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by iandouglas** [waffleio/cardcannon#1]
Hi folks,

Can the installation instructions have more content added? It presumes a lot of prior knowledge.

- Specifically, which permissions do we need to enable for the new GitHub app we need to create?
- Can we get examples of the webhook URL, etc needed for setting up the GitHub app, for when we're hosting on Glitch?
- Can we get some instructions on how we "upload" the project to Glitch? I presume we add Glitch's repo as a 'remote' to our cloned copy of this project, and push to that remote?

**Comment by adamzolyak** [comment]
https://github.com/waffleio/cardcannon/pull/3 feedback appreciated
