### ISSUE TITLE
How to handle rate limiting from GitHub?

### ISSUE THREAD

**Issue by iandouglas** [waffleio/cardcannon#4]
Turns out that 75+ user stories with lots of interdependencies and labels triggers a rate limit on the GitHub API.

Any thoughts on how best to throttle this? Got any contacts at GitHub to find out what this rate limit actually is so I can calculate how best to circumvent this especially if I have a bunch of students trying to run this all at the same time? :)

**Comment by iandouglas** [comment]
Even with a full second pause between creating each story I'm only able to import about 37 stories before GitHub shuts me down. :)

**Comment by iandouglas** [comment]
10 seconds between each new story seems to be more than enough, I'm still dialing in sleeps around the updates for dependencies and such. It'd be nice, though, if the code could see that it's being rate-limited, pause for a while and retry the request on its own (with exponential backoff) instead of shutting down completely. Not sure this is something that comes back in GitHub's headers or not, or how we'd even intercept that.

**Comment by adamzolyak** [comment]
@iandouglas you should be able to interactively [check on rate limits](https://developer.github.com/v3/rate_limit/).  Seems like [GitHub Apps are governed by the same rate limits](https://developer.github.com/apps/building-github-apps/understanding-rate-limits-for-github-apps/) with the potential to earn an increased rate limit for larger organizational users.  I'll also ask my team to see if anyone knows about other rate limiting.  

Please share if you learn more.

**Comment by adamzolyak** [comment]
I got some additional info from GitHub.  There's also an abuse rate limit.  See:

https://developer.github.com/v3/#abuse-rate-limits

https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits

**Comment by adamzolyak** [comment]
Proposed implementation:
* Send requests in batches (ex. 20) with a 1 second pause between batches.
* Check for HTTP 403.  If HTTP 403, check `Retry-After`header.  If exists, wait number of recommended seconds before sending additional requests.

**Comment by iandouglas** [comment]
I like it. I just couldn't find any docs from Probot to look at headers. I posted an issue for them a while back as well at https://github.com/probot/probot/issues/779 but haven't had any response yet.

**Comment by adamzolyak** [comment]
Created #9 as a proposed improvement.  Sorry for moving things around.  This card seemed like a spike (answer some questions and learn about options), so suggest closing it.
