### ISSUE TITLE
CardCannon stopped working on Glitch

### ISSUE THREAD

**Issue by iandouglas** [waffleio/cardcannon#5]
Looks like probot is broken, I started seeing deprecation errors about github.issues.edit being updated to github.issues.update instead but it didn't seem like a name drop-in replacement, and probot/github docs seem out of sync... /sigh

**Comment by adamzolyak** [comment]
Probot uses Octokit Rest for GH API calls.  `issues.editComment` was changed to `issues.updateComment` in [v15.18.0](https://github.com/octokit/rest.js/releases/tag/v15.18.0).  Octokit Rest was also [bumped to the same version](https://github.com/probot/probot/blob/master/package.json#L67) the same day it was released.  I'll try bumping Probot to [v7.4.0](https://github.com/probot/probot/tree/v7.4.0) which has the newer version of Octokit.

**Comment by iandouglas** [comment]
Gotcha. I started looking at Octokit this past week to replicate the code in Ruby, and in doing so I think I found an optimization of the cardcannon code that I'll try to make a PR for shortly. Can't test it easily myself, but should give you an idea.

**Comment by adamzolyak** [comment]
Should be updated in card cannon.

RE using Octokit, I've used Octokit Rest.js and Webhooks.js in some of the [GitHub Actions we're creating](https://github.com/waffleio/waffleio-gh-actions).  It's a good approach - you can effectively do pretty much everything Probot does.

Appreciate suggestions for optimization!
